dist: trusty
sudo: false

language: scala

jdk:
  - openjdk11

scala:
  - 2.13.1
  - 2.12.10

script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls; fi'

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "WP+vYUuOyLiC9/0grbezAV+97fraXCHWLPVsVKPTijLAPX/stkB0dGk92f1T3sP2XjkTPJnnOOwEz2UL1VMCWfBVyJPXMt1ymNQk3ZePk2euW5AphCBPnxfgvDvvsAArT5xQMzS8zw8HSG0EPF7aClpqN2hv5NE19ss+1xNIJhFBb9Eo91KOTf4yhDTYOKwwVgB6t1XEEVek2IKZpRmmpNCnHSVA39jP4sJUudyHEBEZ5jsdWfvR+wT9i2JB9Q8OjZvk2Bs/kTXujvnzCWcLtHc7JGv8o1A6xmU9QwIOI73P6UU2leN2Z4EontQ19NjbHCGO7UIeuQ0FNMly39ywCyP7NLqyYQ19mABigo7pW8isz8Uwha1R0RzLI9kOwSscNQB84Wr8mDg7UQ8QiWaJUQzARMJ3QwMtQAwhUgRJifjC2MYcOBhuyY1cOBfq0bTWLobEmxJ2Dbvk/fuUFmS2TfSGIxWpUFYgYg6Jo05I0yuEx1u68ycPbMPkY5jkfiCcX1y1F5ywSOBpKUcDyKjsiOcNN42TvYu4dRd9uhZcD31288cWdrlL04oQhzg84tw7hDrjUj0M6amH2tDYeDW3Qp+4+FFfkNFOgWKIp5ApCk1OJnwK7nVyQsVV/SkQuC3WRrKpjFzi1TcFmT3CehNLtcawYg54f5zB0UKiIL+5N1E="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
